services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
    volumes:
      - ./mounts/postgres/data:/var/lib/postgresql/data
      - ./mounts/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - preschoolbe
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER:-postgres}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    ports:
      - "${KEYCLOAK_PORT:-28080}:8080"
    command: start-dev
    networks:
      - preschoolbe
    restart: always
    volumes:
      - ./mounts/keycloak/standalone:/opt/keycloak/data

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - '${KAFKA_PORT:-29092}:29092'
    networks:
      - preschoolbe
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://${DOCKER_HOST_IP:-0.0.0.0}:29092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://${DOCKER_HOST_IP:-localhost}:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: 'gqxskHgrT7yG4GzC_x91cg' # bạn có thể random bằng base64(uuid) nếu cần
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1

    volumes:
      - ./mounts/kafka/data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 3

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - ${KAFKA_UI_PORT:-8085}:8080
    networks:
      - preschoolbe
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      kafka:
        condition: service_healthy

  redis:
    image: redis:7.2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./mounts/redis/data:/data
      - ./mounts/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - preschoolbe
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=${REDIS_COMMANDER_USER:-root}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD:-qwerty}
    ports:
      - ${REDIS_COMMANDER_PORT:-8081}:8081
    networks:
      - preschoolbe
    depends_on:
      redis:
        condition: service_healthy

  mongo:
    image: mongo:7.0.9
    ports:
      - ${MONGO_PORT:-27018}:27017
    networks:
      - preschoolbe
    volumes:
      - ./mounts/mongo/data:/data/db
      - ./mounts/mongo/config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  mongo-express:
    image: mongo-express:1.0.2
    ports:
      - ${MONGO_EXPRESS_PORT:-8082}:8081
    networks:
      - preschoolbe
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:-username}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-password}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-password}
    depends_on:
      mongo:
        condition: service_healthy
  localstack:
    image: localstack/localstack:3.3
    container_name: localstack
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566"
      - "${LOCALSTACK_SQS_PORT:-4571}:4571"
      - "${LOCALSTACK_SNS_PORT:-4572}:4572"
      - "${LOCALSTACK_SES_PORT:-4579}:4579"
    environment:
      - SERVICES=s3,sns,sqs,ses
      - EDGE_PORT=4566
      - DEFAULT_REGION=${AWS_REGION:-us-east-1}
      - DATA_DIR=/var/lib/localstack/data
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
    volumes:
      - ./mounts/localstack/data:/var/lib/localstack/data
      - ./mounts/localstack/init:/docker-entrypoint-initaws.d
    networks:
      - preschoolbe
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  oracle:
    image: gvenzl/oracle-xe:18.4.0-slim
    container_name: oracle-xe
    ports:
      - "${ORACLE_PORT:-1521}:1521"
      - "${ORACLE_WEB_PORT:-5500}:5500"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD:-oracle123}     # SYS, SYSTEM, PDBADMIN
      APP_USER: ${ORACLE_USER:-appuser}                  # user cho app (tùy chọn)
      APP_USER_PASSWORD: ${ORACLE_USER_PASSWORD:-apppw}  # mật khẩu user app
    volumes:
      - ./mounts/oracle/data:/opt/oracle/oradata
    networks:
      - preschoolbe
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/${ORACLE_PASSWORD:-oracle123}@localhost/XEPDB1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  preschoolbe:
    driver: bridge